---
- hosts: proxy
  tasks:
  - name: ping
    shell: "ls -l"


- hosts: 127.0.0.1
  vars:
    pipelines:
      main:
        opt1: val1
        opt2: val2
      second:
        opt1: val1
        opt2: val2
    path: "/usr/share/logstash/pipeline/main"
  tasks:
  - set_fact:
      pipelineids: |
        {% set res = [] -%}
        {% for id in pipelines.keys() -%}
          {% for val in pipelines[id].keys() -%}
            {% set ignored = res.extend([{'id': id, val: pipelines[id][val]}]) -%}
          {%- endfor%}
        {%- endfor%}
        {{ res }}
      dir: "{{ path | relpath('/usr/share/logstash/pipeline') }}"
  - debug: var=pipelineids

  - debug:
       msg: "{{ item }} "
    with_items: "{{ pipelines }}"

  - debug:
       msg: "{{ dir }}"
...
