---
instances:
  - assign_public_ip: true
    count_tag:
    security_group_names: "ssh-22,icmp-8"
    ec2_image_id: "ami-026c8acd92718196b"
    exact_count: 1
    instance_tags:
      env: "development"
      provisioner: "ansible"
      Name: "jenkins-dev"
      hostname: "jenkins"
      domain: "dev.devops.io"
    instance_type: "t2.micro"
    ec2_key_name: "2019-ge-se2"
    ec2_monitored: False
    private_ip: "10.5.0.135"
    ec2_region: "us-east-1"
    termination_protection:
    volumes:
    vpc_subnet: "generic-first-dev"
    wait:
    wait_timeout:
    zone:
  - assign_public_ip: true
    count_tag:
    security_group_names: "ssh-22,icmp-8"
    ec2_image_id: "ami-026c8acd92718196b"
    exact_count: 1
    instance_tags:
      env: "development"
      provisioner: "ansible"
      Name: "nexus-dev"
      hostname: "nexus"
      domain: "dev.devops.io"
    instance_type: "t2.micro"
    ec2_key_name: "2019-ge-se2"
    ec2_monitored: False
    private_ip: "10.5.0.5"
    ec2_region: "us-east-1"
    termination_protection:
    volumes:
    vpc_subnet: "generic-second-dev"
    wait:
    wait_timeout:
    zone:
...
