---
ansible_python_interpreter: "/usr/bin/python3"
ansible_ssh_private_key_file: "~/.ssh/keys/aws-2019-2020"
linked_hosts: "{{ groups['all'] | sort }}"
identityfiles:
  - "{{ ansible_ssh_private_key_file }}"
force: true
proxy:
  ssh_user: ''
  ssh_host: ''
  ssh_key: "{{ ansible_ssh_private_key_file }}"
...
