---
secgroups:
  - description: "Allow incoming ssh"
    filters:
    group_id:
    group_name: "ssh-22"
    ip_permissions:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "0.0.0.0/0"
    ip_permissions_egress: []
    purge_rules:
    purge_rules_egress:
    purge_tags:
    tags:
      "env": "development"
      "provisioner": "ansible"
    vpc_name: "generic-dev"
    region: "us-east-1"
  - description: "Allow icmp internal"
    filters:
    group_id:
    group_name: "icmp-8"
    ip_permissions:
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: "0.0.0.0/0"
    ip_permissions_egress: []
    purge_rules:
    purge_rules_egress:
    purge_tags:
    tags:
      "env": "development"
      "provisioner": "ansible"
    vpc_name: "generic-dev"
    region: "us-east-1"
...
