---
subnets:
  - cidr_block: 192.168.5.0/26
    availability_zone: "us-west-2a"
    region: "us-west-2"
    filters:
#      "tag:env": "staging"
#      "tag:provisioner": "ansible"
#      "tag:Name": "gee_dev"
    tags:
      "Name": "gee_dev"
      "env": "staging"
      "provisioner": "ansible"
    vpc_name: "GEE_DEV"
...
