---
plugin: aws_ec2
regions:
  - us-east-1
  - ca-central-1
  - us-east-2
hostnames:
  - tag:Name
  - instance-id
  - private-dns-name
  - dns-name
  - private-ip-address
  - ip-address
filters:
  instance-state-name:
    - pending
    - running
    - shutting-down
    - stopping
    - stopped
compose:
  public_address: fqdn | default(public_ip_address, true)
  private_address: fqdn | default(private_ip_address, true)
  ansible_host: public_address | default(private_address, true)
  provider: 'aws'
#groups:
#  ec2: true
...
