---
#ansible_python_interpreter: "/usr/bin/python3"
#ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -q {{ proxy.ssh_user }}@{{ proxy.ssh_host }}'"
key_name: default-2019-2020
ansible_ssh_private_key_file: "~/.ssh/keys/{{ key_name }}"
zone: "dongmo.fr"
fqdn: "{{ inventory_hostname }}.{{ zone }}"
mail: "service@{{ zone }}"
ansible_host: "{{ fqdn }}"
identityfiles:
  - "{{ ansible_ssh_private_key_file }}"
ldaps:
  - node: x.x.x.x
    port: 389
#proxy:
#  ssh_user: ''
#  ssh_host: ''
#  ssh_key: "~/.ssh/key/proxy"
force: true
linked_hosts: "{{ groups['all'] | sort }}"
...
