---
ansible_ssh_private_key_file: "~/.ssh/keys/{{ ec2_key_name }}"
zone: "testzone.io"
ip_address: "{{ ec2_ip_address | default(inventory_hostname) }}"
fqdn: "{{ inventory_hostname }}.{{ zone }}"
...
